### ISSUE TITLE
cannot compile for amd64

### ISSUE THREAD

**Issue by krawalli** [frafall/service.snapcast#2]
Seems that dependencies missing.

I've added "alsa-lib" and "avahi", now it compiles further on but stops with:
~~~
In file included from controller.cpp:24:0:
decoder/oggDecoder.h:23:10: fatal error: tremor/ivorbiscodec.h: No such file or directory
 #include <tremor/ivorbiscodec.h>
~~~

Can you give me a hint what the depency is for that?

**Comment by frafall** [comment]
Hmm, what version of Libreelec are you compiling against? I had some new issues when upgrading to 8.1.2.

Does the file exist in externals/tremor?

What's your PROJECT/ARCH environment set to (so I can try to reproduce)

**Comment by krawalli** [comment]
It's latest LibreELEC from git as its written in README:
~~~
...
To compile this addon you need to:
Clone Libreelec:

$ git clone https://github.com/LibreELEC/LibreELEC.tv.git
...
~~~

Hmm maybe I should checkout 8.2 series....

Yes: external and subdirs exists. IT seems they are never compiled and so the libs are not found/used

I tried to compile with
~~~bash
PROJECT=Generic ARCH=x86_64 scripts/create_addon snapcast
~~~

**Comment by frafall** [comment]
I've started a generic build to test, based it on 8.2.1

**Comment by frafall** [comment]
I've merged two patches I built earlier on my metadata branch (ie coming version). I have not tested compiling them outside that branch yet, it takes a little time to get the x86_64 build ready :( 

But, in the metadata branch these resolved the tremor issue.

**Comment by ariendj** [comment]
I successfully built snapcast for x86_64 against LE's master branch. Got the same error as @krawalli got.
In oggDecoder.h I made the following change:
`#ifdef HAS_TREMOR
#include <externals/tremor/ivorbiscodec.h>
#else
#include <externals/vorbis/codec.h>
#endif`
So I added 'externals/' before 'tremor/ivorbiscodec.h' and before 'vorbis/codec.h'. The addon could be built after making that change.

**Comment by ariendj** [comment]
[service.snapcast-9.0.4.zip](https://github.com/frafall/service.snapcast/files/1591145/service.snapcast-9.0.4.zip)
Here's the resulting binary.
Edit: Got around to trying it out. Snapserver works, although I had to start it manually. I can't test snapclient as I use pulseaudio and that's not supported by snapclient.

**Comment by frafall** [comment]
Well, you should be able to run snapclient with the underlaying ALSA api

**Comment by ariendj** [comment]
Yes that should be possible. At the moment I use pulseaudio to play audio on a remote machine with speakers attached. Unfortunately this does not work with alsa only. I'll try the snapclient binary out with alsa only in the new year but I'm pretty sure it will work just fine.

**Comment by msebald** [comment]
@ariendj Just wanted to mention that I was able to use your x86_64 build on my x86_64 LibreELEC box. I am using the Milhouse test build with Kodi 18 from today.
